### ISSUE TITLE
dump.to_datahub

### ISSUE THREAD

**Issue by zelima** [datahq/datapackage-pipelines-datahub#2]
This would basically be a python version of https://github.com/datahq/datahub-cli/blob/master/lib/utils/datahub.js#L25 - though you might need to push one file at a time

But as an alternative, For now, we can use the data CLI by hand for now - it is operational.  Meaning processor should expect that `datahub cli` is installed and working on the machine and it python script should just invoke `data push ...` command 

## Acceptance criteria 

* [x] Able to push with dpp: `- run datahub.dump.to_datahub` in pipeline-spec.yaml

## Tasks

* [x] add new processor
* [ ] Test it (not sure how test would look like and what it should test, or how)

**Comment by zelima** [comment]
FIXED though test are missing
